remove comment for error valid dict -- error was just content-type to plain/txt instead of json in headers & put back dict(post) since error when sending the request - TypeError: update() got an unexpected keyword argument 'title'